// Additional rewards, in atlas row-major order after the first six.
// Each label is [English, Spanish, French, Russian].
export const additionalItems = {
  dinosaurs: [
    ['Spinosaurus','Espinosaurio','Spinosaure','Спинозавр'],
    ['Ankylosaurus','Anquilosaurio','Ankylosaure','Анкилозавр'],
    ['Parasaurolophus','Parasaurolofo','Parasaurolophus','Паразауролоф'],
    ['Velociraptor','Velociraptor','Vélociraptor','Велоцираптор'],
    ['Plesiosaur','Plesiosaurio','Plésiosaure','Плезиозавр'],
    ['Dimetrodon','Dimetrodón','Dimétrodon','Диметродон'],
    ['Pachycephalosaurus','Paquicefalosaurio','Pachycéphalosaure','Пахицефалозавр'],
    ['Iguanodon','Iguanodón','Iguanodon','Игуанодон'],
    ['Diplodocus','Diplodoco','Diplodocus','Диплодок'],
    ['Carnotaurus','Carnotauro','Carnotaure','Карнотавр'],
    ['Mosasaur','Mosasaurio','Mosasaure','Мозазавр'],
    ['Archaeopteryx','Arqueópterix','Archéoptéryx','Археоптерикс'],
    ['Fossil footprint','Huella fósil','Empreinte fossile','Окаменевший след'],
    ['Ammonite','Amonita','Ammonite','Аммонит'],
    ['Amber','Ámbar','Ambre','Янтарь'],
    ['Fossil tooth','Diente fósil','Dent fossile','Окаменевший зуб'],
    ['Volcano','Volcán','Volcan','Вулкан'],
    ['Prehistoric fern','Helecho prehistórico','Fougère préhistorique','Древний папоротник'],
    ['Palm tree','Palmera','Palmier','Пальма'],
    ['Dinosaur nest','Nido de dinosaurio','Nid de dinosaure','Гнездо динозавра'],
    ['Explorer hat','Sombrero de explorador','Chapeau d’explorateur','Шляпа исследователя'],
    ['Excavation brush','Pincel de excavación','Pinceau de fouille','Кисточка для раскопок'],
    ['Fossil hammer','Martillo de fósiles','Marteau à fossiles','Молоток для раскопок'],
    ['Dinosaur skull','Cráneo de dinosaurio','Crâne de dinosaure','Череп динозавра']
  ],
  space: [
    ['Astronaut','Astronauta','Astronaute','Космонавт'],
    ['Space station','Estación espacial','Station spatiale','Космическая станция'],
    ['Flying saucer','Platillo volante','Soucoupe volante','Летающая тарелка'],
    ['Telescope','Telescopio','Télescope','Телескоп'],
    ['Sun','Sol','Soleil','Солнце'],
    ['Crescent moon','Luna creciente','Croissant de lune','Месяц'],
    ['Earth','Tierra','Terre','Земля'],
    ['Mars','Marte','Mars','Марс'],
    ['Comet','Cometa','Comète','Комета'],
    ['Meteorite','Meteorito','Météorite','Метеорит'],
    ['Galaxy','Galaxia','Galaxie','Галактика'],
    ['Shooting star','Estrella fugaz','Étoile filante','Падающая звезда'],
    ['Space shuttle','Transbordador espacial','Navette spatiale','Космический шаттл'],
    ['Lunar lander','Módulo lunar','Module lunaire','Лунный модуль'],
    ['Radio dish','Antena parabólica','Antenne parabolique','Радиоантенна'],
    ['Solar panel','Panel solar','Panneau solaire','Солнечная батарея'],
    ['Robot astronaut','Robot astronauta','Robot astronaute','Робот-космонавт'],
    ['Space boot','Bota espacial','Botte spatiale','Космический ботинок'],
    ['Space glove','Guante espacial','Gant spatial','Космическая перчатка'],
    ['Oxygen backpack','Mochila de oxígeno','Sac à oxygène','Кислородный ранец'],
    ['Alien crystal','Cristal extraterrestre','Cristal extraterrestre','Инопланетный кристалл'],
    ['Star medal','Medalla de estrella','Médaille étoilée','Звёздная медаль'],
    ['Mission flag','Bandera de misión','Drapeau de mission','Флаг экспедиции'],
    ['Moon rock','Roca lunar','Pierre lunaire','Лунный камень']
  ],
  unicorns: [
    ['Baby unicorn','Bebé unicornio','Bébé licorne','Малыш-единорог'],
    ['Winged unicorn','Unicornio alado','Licorne ailée','Крылатый единорог'],
    ['Purple unicorn','Unicornio morado','Licorne violette','Фиолетовый единорог'],
    ['Golden unicorn','Unicornio dorado','Licorne dorée','Золотой единорог'],
    ['Rainbow unicorn','Unicornio arcoíris','Licorne arc-en-ciel','Радужный единорог'],
    ['Sleeping unicorn','Unicornio dormido','Licorne endormie','Спящий единорог'],
    ['Rainbow crown','Corona arcoíris','Couronne arc-en-ciel','Радужная корона'],
    ['Star wand','Varita de estrella','Baguette étoilée','Звёздная палочка'],
    ['Heart gem','Gema de corazón','Gemme en cœur','Сердце-самоцвет'],
    ['Rainbow cupcake','Pastelito arcoíris','Petit gâteau arc-en-ciel','Радужный кекс'],
    ['Cloud carriage','Carroza de nubes','Carrosse de nuages','Облачная карета'],
    ['Unicorn snow globe','Bola de nieve de unicornio','Boule à neige licorne','Снежный шар с единорогом'],
    ['Sparkling horseshoe','Herradura brillante','Fer à cheval scintillant','Сверкающая подкова'],
    ['Rainbow bridge','Puente arcoíris','Pont arc-en-ciel','Радужный мост'],
    ['Star pillow','Cojín de estrella','Coussin étoile','Подушка-звезда'],
    ['Rainbow kite','Cometa arcoíris','Cerf-volant arc-en-ciel','Радужный воздушный змей'],
    ['Heart balloon','Globo de corazón','Ballon en cœur','Шарик-сердечко'],
    ['Rainbow key','Llave arcoíris','Clé arc-en-ciel','Радужный ключ'],
    ['Pearl shell','Concha con perla','Coquillage à perle','Ракушка с жемчужиной'],
    ['Crystal flower','Flor de cristal','Fleur de cristal','Хрустальный цветок'],
    ['Rainbow butterfly','Mariposa arcoíris','Papillon arc-en-ciel','Радужная бабочка'],
    ['Star music box','Caja musical de estrella','Boîte à musique étoilée','Звёздная музыкальная шкатулка'],
    ['Rainbow potion','Poción arcoíris','Potion arc-en-ciel','Радужное зелье'],
    ['Unicorn treasure chest','Cofre de unicornio','Coffre de licorne','Сундук единорога']
  ],
  fairies: [
    ['Water fairy','Hada del agua','Fée de l’eau','Водная фея'],
    ['Sun fairy','Hada del sol','Fée du soleil','Солнечная фея'],
    ['Snow fairy','Hada de la nieve','Fée des neiges','Снежная фея'],
    ['Rose fairy','Hada de las rosas','Fée des roses','Фея роз'],
    ['Night fairy','Hada de la noche','Fée de la nuit','Ночная фея'],
    ['Autumn fairy','Hada del otoño','Fée de l’automne','Осенняя фея'],
    ['Leaf boat','Barco de hoja','Bateau de feuille','Лодочка-листик'],
    ['Acorn teapot','Tetera de bellota','Théière gland','Чайник-жёлудь'],
    ['Flower cup','Taza de flor','Tasse fleur','Чашка-цветок'],
    ['Fairy door','Puerta de hada','Porte de fée','Дверца феи'],
    ['Crystal key','Llave de cristal','Clé de cristal','Хрустальный ключ'],
    ['Fairy boots','Botas de hada','Bottes de fée','Сапожки феи'],
    ['Moon pendant','Colgante de luna','Pendentif lune','Лунный кулон'],
    ['Dewdrop gem','Gema de rocío','Gemme de rosée','Самоцвет-росинка'],
    ['Firefly','Luciérnaga','Luciole','Светлячок'],
    ['Magic snail','Caracol mágico','Escargot magique','Волшебная улитка'],
    ['Flower ladybug','Mariquita con flor','Coccinelle fleurie','Божья коровка с цветком'],
    ['Dragonfly','Libélula','Libellule','Стрекоза'],
    ['Spell book','Libro de hechizos','Livre de sorts','Книга заклинаний'],
    ['Magic potion','Poción mágica','Potion magique','Волшебное зелье'],
    ['Leaf umbrella','Paraguas de hoja','Parapluie feuille','Зонтик-листик'],
    ['Flower chair','Silla de flor','Chaise fleur','Стульчик-цветок'],
    ['Fairy bell','Campana de hada','Clochette de fée','Колокольчик феи'],
    ['Fairy treasure chest','Cofre de hada','Coffre de fée','Сундук феи']
  ],
  garden: [
    ['Rose','Rosa','Rose','Роза'],
    ['Daisy','Margarita','Marguerite','Ромашка'],
    ['Lavender','Lavanda','Lavande','Лаванда'],
    ['Orchid','Orquídea','Orchidée','Орхидея'],
    ['Daffodil','Narciso','Jonquille','Нарцисс'],
    ['Bluebell','Campanilla','Jacinthe des bois','Колокольчик'],
    ['Violet','Violeta','Violette','Фиалка'],
    ['Peony','Peonía','Pivoine','Пион'],
    ['Cactus','Cactus','Cactus','Кактус'],
    ['Cherry blossom','Flor de cerezo','Fleur de cerisier','Цветущая вишня'],
    ['Apple tree','Manzano','Pommier','Яблоня'],
    ['Lemon tree','Limonero','Citronnier','Лимонное дерево'],
    ['Carrots','Zanahorias','Carottes','Морковки'],
    ['Pumpkin','Calabaza','Citrouille','Тыква'],
    ['Pea pod','Vaina de guisantes','Gousse de petits pois','Стручок гороха'],
    ['Garden trowel','Palita de jardín','Transplantoir','Садовая лопатка'],
    ['Garden rake','Rastrillo','Râteau','Грабли'],
    ['Gardening gloves','Guantes de jardín','Gants de jardinage','Садовые перчатки'],
    ['Wheelbarrow','Carretilla','Brouette','Тачка'],
    ['Birdhouse','Casita de pájaros','Nichoir','Скворечник'],
    ['Bumblebee','Abejorro','Bourdon','Шмель'],
    ['Snail','Caracol','Escargot','Улитка'],
    ['Garden gnome','Gnomo de jardín','Nain de jardin','Садовый гном'],
    ['Flower seeds','Semillas de flores','Graines de fleurs','Семена цветов']
  ]
};
